path_tolerance: 0.001
goal_tolerance: 0.0

  
home:
  positions:
  - [0.0, 0.0,     0.0, 0.0, 0.0, 0.0]
  - [0.0, -0.2, 0.0, 0.0, 0.0, 0.0]
  - [0.0, -0.7, 0.0, 0.0, 0.0, 0.0]
  - [0.0, -0.8, 0.0, 0.0, 0.0, 0.0]
  - [0.0, -0.8, 0.0, 0.0, 0.0, 0.0]
  - [0.0,  0.0, 0.0, 0.0, 0.0, 0.0]
  velocities:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, -0.1, 0.0, 0.0, 0.0, 0.0]
  - [0.0, -0.1, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  time_from_start:
  - 0.0
  - 4.0
  - 9.0
  - 11.0
  - 16.0
  - 20.0
  joint_names:
  - ur10_shoulder_pan_joint
  - ur10_shoulder_lift_joint
  - ur10_elbow_joint
  - ur10_wrist_1_joint
  - ur10_wrist_2_joint
  - ur10_wrist_3_joint


trj1:
  positions:
  - [0.0, 0.0,     0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.01, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0,     0.0, 0.0, 0.0, 0.0]
  velocities:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  time_from_start:
  - 0.0
  - 0.05
  - 0.1
  joint_names:
  - ur10_shoulder_pan_joint
  - ur10_shoulder_lift_joint
  - ur10_elbow_joint
  - ur10_wrist_1_joint
  - ur10_wrist_2_joint
  - ur10_wrist_3_joint

